version: "3.9"

networks:
  rinhabackend:

services:

  database:
    container_name: database
    image: 'postgres:latest'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.7GB'
    ports:
       - 5432:5432
    environment:
       POSTGRES_USER: rinha
       POSTGRES_PASSWORD: k8M9ODJ7d19FCs
       POSTGRES_DB: rinha-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
     - rinhabackend

  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.4GB'
    networks:
     - rinhabackend