name: dotnet-workflow

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  publish-docker:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_IMAGE_NAME: isaacnborges/rinha-api
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker image build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.DOCKER_IMAGE_NAME }}:latest -f src/Dockerfile .

      - name: Push Docker image
        run: docker image push --all-tags ${{ env.DOCKER_IMAGE_NAME }}

  stress-test:
    name: Gatling Stress Test
    runs-on: ubuntu-20.04
    needs: publish-docker
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose up -d
    - name: Load test
      run: |
        git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2023-q3
        cd rinha-de-backend-2023-q3
        wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
        unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
        cd gatling-charts-highcharts-bundle-3.9.5
        ./bin/gatling.sh -rm local -s RinhaBackendSimulation -rd "DESCRICAO" -rf $WORKSPACE/user-files/results -sf $WORKSPACE/user-files/simulations -rsf $WORKSPACE/user-files/resources
        echo GATLING_OUTPUT_FOLDER=$(ls $WORKSPACE/user-files/results | sort | head -n 1) >> $GITHUB_ENV
      env:
        WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test
    - run: echo ${{ env.GATLING_OUTPUT_FOLDER }}
    - run: |
        # replace string DESCRICAO with the commit sha in file index.html inside GATLING OUTPUT FOLDER
        sed -i "s/DESCRICAO/${{ github.sha }}/g" ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}  
        destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}
    - run: echo "GH_REPO=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
    - run: echo "[Deploying to https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/results/${{ env.GATLING_OUTPUT_FOLDER }}](https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/results/${{ env.GATLING_OUTPUT_FOLDER }})" >> "${GITHUB_STEP_SUMMARY}"